services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Optional: prefill the connection target in the UI
      ADMINER_DEFAULT_SERVER: db
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ..
      dockerfile: ./docker/py.Dockerfile
    #environment:
    #  DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
    #  DATA_DIR: /data
    #  CLIP_MODEL_NAME: openai/clip-vit-base-patch32
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data:/data
      # - ../../clip-image-search/data/dataset_temp:/data/dataset
      # - ../:/app
    #tty: true
    #entrypoint:
    #  - "bash"
volumes:
  pgdata:
